// SPDX-License-Identifier: LGPL-2.0-or-later
// Copyright © EDF R&D / TELECOM ParisTech (ENST-TSI)

#ifndef CC_CORE_LIB_HEADER
#define CC_CORE_LIB_HEADER

#ifdef _MSC_VER
//To get rid of the really annoying warnings about template class exportation
#pragma warning( disable: 4251 )
#pragma warning( disable: 4530 )
#endif

// this file is generated by cmake
#include "CCCoreLibExport.h"

#endif //CC_CORE_LIB_HEADER
