// SPDX-License-Identifier: LGPL-2.0-or-later
// Copyright © EDF R&D / TELECOM ParisTech (ENST-TSI)

#pragma once

#ifdef _MSC_VER
//To get rid of the really annoying warnings about template class exportation
#pragma warning( disable: 4251 )
#pragma warning( disable: 4530 )
//To get rid of the new warnings in Qt 5.15
#pragma warning( disable: 4996 )
#endif

// this file is generated by cmake
#include "CCCoreLibExport.h"
